# Generated by Django 3.1.3 on 2021-07-25 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=800)),
                ('quantity', models.CharField(max_length=300)),
                ('action', models.CharField(choices=[('BOUGHT', 'item_bought'), ('NOT AVAILABLE', 'item_end'), ('PENDING', 'in_queue')], max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
