# Generated by Django 3.1.3 on 2021-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
